#!/usr/bin/env php
<?php

require __DIR__ . '/vendor/autoload.php';

use Symfony\Component\Console\Application;
use BBLDN\LaravelDbmlGenerator\Infrastructure\Command\Command;

$application = new Application('Laravel Scheme Tool', '0.1.0');

$command = new Command();
$application->add($command);
$application->setDefaultCommand($command->getName(), true);

$application->run();
